#!/bin/bash
###### Check Zombie process older than X time
###### Script by Andrea Cervesato

if [ $# -lt 3 ]; then
	echo "Utilizzo:"
	echo " $0 warning_level critical_level older_than_secs"
	echo " Esempio: $0 10 15 900"
	exit 1
fi
nome="ZOMBIE"
warning=$1
critical=$2
older=$3
################################################################################################################################
# Tipo di processi da greppare (zombie)
grep_procs="z,Z,+z,+Z"
################################################################################################################################
count=0
for procs in $(ps -eo stat,pid,etime --sort start_time|grep ^[$grep_procs]|awk '{print $3}'); do
	secs="$(echo $procs|sed 's/:\|-/ /g;' |awk '{print $4" "$3" "$2" "$1}' | awk '{print $1+$2*60+$3*3600+$4*86400}')"
	if [ $secs -gt $older ]; then
		let count=$count+1
	fi
done
if [ $count -gt $warning ]; then
	if [ $count -lt $critical ]; then
		echo $nome WARNING: $count zombie procs older than $older
		exit 1
	else
		echo $nome CRITICAL: $count zombie procs older than $older
		exit 2
	fi
else
	echo $nome OK: $count zombie procs older than $older
	exit 0
fi
